- name: app setup for application {{component}}
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup
- name : importing nodejs setup application
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs-setup
- name: copying config file
  ansible.builtin.template:
    src: cart.service.j2
    dest: /etc/systemd/system/{{component}}.service
- name: system deamon reload
  ansible.builtin.systemd_service:
    daemon_reload: true
- name: start and enable cart
  ansible.builtin.service:
    name: cart
    state: started
    enabled: yes
