- name: installing cart
  hosts: cart
  become: yes
  tasks:
    - name: disable and enable nodejs
      ansible.builtin.shell: dnf module disable nodejs -y;dnf module enable nodejs:18 -y
    - name: installing nodjs
      ansible.builtin.package:
        name: nodejs
        state: present
    - name: adding user
      ansible.builtin.user:
        name: roboshop
    - name: creating app directory
      ansible.builtin.file:
        path: /app
        state: directory
    - name: download application from url 
      ansible.builtin.get_url:
        url: https://roboshop-builds.s3.amazonaws.com/cart.zip
        dest: /tmp/cart.zip
    - name: unarchive the zip file
      ansible.builtin.unarchive:
        src:  /tmp/cart.zip
        dest: /app
        remote_src: yes
    - name: install dependencies 
      ansible.builtin.command: npm install
      args:
        chdir: /app
    - name: copying config file
      ansible.builtin.copy:
        src: cart.service
        dest: /etc/systemd/system/cart.service
    - name: system deamon reload
      ansible.builtin.systemd_service:
        daemon_reload: true
    - name: enable and starting cart
      ansible.builtin.service:
        name: cart
        state: started
        enabled: yes